### ISSUE TITLE
rake error

### ISSUE THREAD

**Issue by lyatziv** [spot-us/spot-us#1]
On a fresh install ubuntu server 9.07 ruby and rails set up running and tested
spot-us files in a good home and to make sure I have all the gems I need, I run

sudo rake gems:install

Gives an error
Undefined method `clear' for <Rake::Task default => [test]>:Rake::Task

Checking the task 'clear_test_default.rake'
it seems to look for a test script in the default rails dir (2.3.2)
/usr/lib/ruby/gems/1.8/gems/rails-2.3.2

Do I need to make a change?

**Comment by lyatziv** [comment]
It's easy
Downgrade Rake to 0.8.4
also make sure to check the Wiki for all the versions of the Gems you will need

**Comment by Sophrinix** [comment]
this should also be closed.
