### ISSUE TITLE
 RightAws::AwsError in Admin/channelsController#create 

### ISSUE THREAD

**Issue by devenpatel** [spot-us/spot-us#3]
RightAws::AwsError in Admin/channelsController#create

AWS access keys are required to operate on S3

RAILS_ROOT: /home/deven/rweb/project/spot-us
Application Trace | Framework Trace | Full Trace

/home/deven/rweb/project/spot-us/vendor/plugins/right_aws/lib/awsbase/right_awsbase.rb:217:in `init'
/home/deven/rweb/project/spot-us/vendor/plugins/right_aws/lib/s3/right_s3_interface.rb:81:in`initialize'
/home/deven/rweb/project/spot-us/vendor/plugins/right_aws/lib/s3/right_s3.rb:65:in `new'
/home/deven/rweb/project/spot-us/vendor/plugins/right_aws/lib/s3/right_s3.rb:65:in`initialize'
/home/deven/rweb/project/spot-us/vendor/plugins/paperclip/lib/paperclip/storage.rb:128:in `new'
/home/deven/rweb/project/spot-us/vendor/plugins/paperclip/lib/paperclip/storage.rb:128:in`s3'
/home/deven/rweb/project/spot-us/vendor/plugins/paperclip/lib/paperclip/storage.rb:134:in `s3_bucket'
/home/deven/rweb/project/spot-us/vendor/plugins/paperclip/lib/paperclip/storage.rb:166:in`flush_writes'
/home/deven/rweb/project/spot-us/vendor/plugins/paperclip/lib/paperclip/storage.rb:163:in `each'
/home/deven/rweb/project/spot-us/vendor/plugins/paperclip/lib/paperclip/storage.rb:163:in`flush_writes'
/home/deven/rweb/project/spot-us/vendor/plugins/paperclip/lib/paperclip/attachment.rb:138:in `save'
/home/deven/rweb/project/spot-us/vendor/plugins/paperclip/lib/paperclip.rb:242:in`send'
/home/deven/rweb/project/spot-us/vendor/plugins/paperclip/lib/paperclip.rb:242:in `save_attached_files'
/home/deven/rweb/project/spot-us/vendor/plugins/paperclip/lib/paperclip.rb:235:in`each_attachment'
/home/deven/rweb/project/spot-us/vendor/plugins/paperclip/lib/paperclip.rb:234:in `each'
/home/deven/rweb/project/spot-us/vendor/plugins/paperclip/lib/paperclip.rb:234:in`each_attachment'
/home/deven/rweb/project/spot-us/vendor/plugins/paperclip/lib/paperclip.rb:241:in `save_attached_files'
/usr/lib64/ruby/gems/1.8/gems/activesupport-2.3.2/lib/active_support/callbacks.rb:178:in`send'
/usr/lib64/ruby/gems/1.8/gems/activesupport-2.3.2/lib/active_support/callbacks.rb:178:in `evaluate_method'
/usr/lib64/ruby/gems/1.8/gems/activesupport-2.3.2/lib/active_support/callbacks.rb:166:in`call'
/usr/lib64/ruby/gems/1.8/gems/activesupport-2.3.2/lib/active_support/callbacks.rb:93:in `run'
/usr/lib64/ruby/gems/1.8/gems/activesupport-2.3.2/lib/active_support/callbacks.rb:92:in`each'
/usr/lib64/ruby/gems/1.8/gems/activesupport-2.3.2/lib/active_support/callbacks.rb:92:in `send'
/usr/lib64/ruby/gems/1.8/gems/activesupport-2.3.2/lib/active_support/callbacks.rb:92:in`run'
/usr/lib64/ruby/gems/1.8/gems/activesupport-2.3.2/lib/active_support/callbacks.rb:276:in `run_callbacks'
/usr/lib64/ruby/gems/1.8/gems/activerecord-2.3.2/lib/active_record/callbacks.rb:344:in`callback'
/usr/lib64/ruby/gems/1.8/gems/activerecord-2.3.2/lib/active_record/callbacks.rb:251:in `create_or_update'
/usr/lib64/ruby/gems/1.8/gems/activerecord-2.3.2/lib/active_record/base.rb:2539:in`save_without_validation'
/usr/lib64/ruby/gems/1.8/gems/activerecord-2.3.2/lib/active_record/validations.rb:1009:in `save_without_dirty'
/usr/lib64/ruby/gems/1.8/gems/activerecord-2.3.2/lib/active_record/dirty.rb:79:in`save_without_transactions'
/usr/lib64/ruby/gems/1.8/gems/activerecord-2.3.2/lib/active_record/transactions.rb:229:in `send'
/usr/lib64/ruby/gems/1.8/gems/activerecord-2.3.2/lib/active_record/transactions.rb:229:in`with_transaction_returning_status'
/usr/lib64/ruby/gems/1.8/gems/activerecord-2.3.2/lib/active_record/connection_adapters/abstract/database_statements.rb:136:in `transaction'
/usr/lib64/ruby/gems/1.8/gems/activerecord-2.3.2/lib/active_record/transactions.rb:182:in`transaction'
/usr/lib64/ruby/gems/1.8/gems/activerecord-2.3.2/lib/active_record/transactions.rb:228:in `with_transaction_returning_status'
/usr/lib64/ruby/gems/1.8/gems/activerecord-2.3.2/lib/active_record/transactions.rb:196:in`save'
/usr/lib64/ruby/gems/1.8/gems/activerecord-2.3.2/lib/active_record/transactions.rb:208:in `rollback_active_record_state!'
/usr/lib64/ruby/gems/1.8/gems/activerecord-2.3.2/lib/active_record/transactions.rb:196:in`save'
/home/deven/rweb/project/spot-us/vendor/plugins/response_for_rc/lib/ardes/response_for_rc/actions.rb:39:in `create'
/usr/lib64/ruby/gems/1.8/gems/actionpack-2.3.2/lib/action_controller/base.rb:1322:in`send'
/usr/lib64/ruby/gems/1.8/gems/actionpack-2.3.2/lib/action_controller/base.rb:1322:in `perform_action_without_filters'
/usr/lib64/ruby/gems/1.8/gems/actionpack-2.3.2/lib/action_controller/filters.rb:617:in`call_filters'
/usr/lib64/ruby/gems/1.8/gems/actionpack-2.3.2/lib/action_controller/filters.rb:610:in `perform_action_without_benchmark'
/usr/lib64/ruby/gems/1.8/gems/actionpack-2.3.2/lib/action_controller/benchmarking.rb:68:in`perform_action_without_rescue'
/usr/lib64/ruby/gems/1.8/gems/activesupport-2.3.2/lib/active_support/core_ext/benchmark.rb:17:in `ms'
/usr/lib64/ruby/gems/1.8/gems/activesupport-2.3.2/lib/active_support/core_ext/benchmark.rb:10:in`realtime'
/usr/lib64/ruby/gems/1.8/gems/activesupport-2.3.2/lib/active_support/core_ext/benchmark.rb:17:in `ms'
/usr/lib64/ruby/gems/1.8/gems/actionpack-2.3.2/lib/action_controller/benchmarking.rb:68:in`perform_action_without_rescue'
/usr/lib64/ruby/gems/1.8/gems/actionpack-2.3.2/lib/action_controller/rescue.rb:160:in `perform_action_without_flash'
/usr/lib64/ruby/gems/1.8/gems/actionpack-2.3.2/lib/action_controller/flash.rb:141:in`perform_action'
/usr/lib64/ruby/gems/1.8/gems/actionpack-2.3.2/lib/action_controller/base.rb:523:in `send'
/usr/lib64/ruby/gems/1.8/gems/actionpack-2.3.2/lib/action_controller/base.rb:523:in`process_without_filters'
/usr/lib64/ruby/gems/1.8/gems/actionpack-2.3.2/lib/action_controller/filters.rb:606:in `sass_old_process'
/usr/lib64/ruby/gems/1.8/gems/haml-2.2.16/lib/sass/plugin/rails.rb:19:in`process'
/usr/lib64/ruby/gems/1.8/gems/actionpack-2.3.2/lib/action_controller/base.rb:391:in `process'
/usr/lib64/ruby/gems/1.8/gems/actionpack-2.3.2/lib/action_controller/base.rb:386:in`call'
/usr/lib64/ruby/gems/1.8/gems/actionpack-2.3.2/lib/action_controller/routing/route_set.rb:433:in `call'
/usr/lib64/ruby/gems/1.8/gems/actionpack-2.3.2/lib/action_controller/dispatcher.rb:88:in`dispatch'
/usr/lib64/ruby/gems/1.8/gems/actionpack-2.3.2/lib/action_controller/dispatcher.rb:111:in `_call'
/usr/lib64/ruby/gems/1.8/gems/actionpack-2.3.2/lib/action_controller/dispatcher.rb:82:in`initialize'
/usr/lib64/ruby/gems/1.8/gems/activerecord-2.3.2/lib/active_record/query_cache.rb:29:in `call'
/usr/lib64/ruby/gems/1.8/gems/activerecord-2.3.2/lib/active_record/query_cache.rb:29:in`call'
/usr/lib64/ruby/gems/1.8/gems/activerecord-2.3.2/lib/active_record/connection_adapters/abstract/query_cache.rb:34:in `cache'
/usr/lib64/ruby/gems/1.8/gems/activerecord-2.3.2/lib/active_record/query_cache.rb:9:in`cache'
/usr/lib64/ruby/gems/1.8/gems/activerecord-2.3.2/lib/active_record/query_cache.rb:28:in `call'
/usr/lib64/ruby/gems/1.8/gems/activerecord-2.3.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:361:in`call'
/usr/lib64/ruby/gems/1.8/gems/rack-1.0.1/lib/rack/head.rb:9:in `call'
/usr/lib64/ruby/gems/1.8/gems/rack-1.0.1/lib/rack/methodoverride.rb:24:in`call'
/usr/lib64/ruby/gems/1.8/gems/actionpack-2.3.2/lib/action_controller/params_parser.rb:15:in `call'
/home/deven/rweb/project/spot-us/vendor/plugins/facebooker/lib/rack/facebook.rb:43:in`call'
/usr/lib64/ruby/gems/1.8/gems/actionpack-2.3.2/lib/action_controller/rewindable_input.rb:25:in `call'
/usr/lib64/ruby/gems/1.8/gems/actionpack-2.3.2/lib/action_controller/session/cookie_store.rb:93:in`call'
/usr/lib64/ruby/gems/1.8/gems/actionpack-2.3.2/lib/action_controller/reloader.rb:9:in `call'
/usr/lib64/ruby/gems/1.8/gems/actionpack-2.3.2/lib/action_controller/failsafe.rb:11:in`call'
/usr/lib64/ruby/gems/1.8/gems/rack-1.0.1/lib/rack/lock.rb:11:in `call'
/usr/lib64/ruby/gems/1.8/gems/rack-1.0.1/lib/rack/lock.rb:11:in`synchronize'
/usr/lib64/ruby/gems/1.8/gems/rack-1.0.1/lib/rack/lock.rb:11:in `call'
/usr/lib64/ruby/gems/1.8/gems/actionpack-2.3.2/lib/action_controller/dispatcher.rb:106:in`call'
/usr/lib64/ruby/gems/1.8/gems/rails-2.3.2/lib/rails/rack/static.rb:31:in `call'
/usr/lib64/ruby/gems/1.8/gems/rack-1.0.1/lib/rack/urlmap.rb:46:in`call'
/usr/lib64/ruby/gems/1.8/gems/rack-1.0.1/lib/rack/urlmap.rb:40:in `each'
/usr/lib64/ruby/gems/1.8/gems/rack-1.0.1/lib/rack/urlmap.rb:40:in`call'
/usr/lib64/ruby/gems/1.8/gems/rails-2.3.2/lib/rails/rack/log_tailer.rb:17:in `call'
/usr/lib64/ruby/gems/1.8/gems/rack-1.0.1/lib/rack/content_length.rb:13:in`call'
/usr/lib64/ruby/gems/1.8/gems/rack-1.0.1/lib/rack/handler/webrick.rb:50:in `service'
/usr/lib/ruby/1.8/webrick/httpserver.rb:104:in`service'
/usr/lib/ruby/1.8/webrick/httpserver.rb:65:in `run'
/usr/lib/ruby/1.8/webrick/server.rb:173:in`start_thread'
/usr/lib/ruby/1.8/webrick/server.rb:162:in `start'
/usr/lib/ruby/1.8/webrick/server.rb:162:in`start_thread'
/usr/lib/ruby/1.8/webrick/server.rb:95:in `start'
/usr/lib/ruby/1.8/webrick/server.rb:92:in`each'
/usr/lib/ruby/1.8/webrick/server.rb:92:in `start'
/usr/lib/ruby/1.8/webrick/server.rb:23:in`start'
/usr/lib/ruby/1.8/webrick/server.rb:82:in `start'
/usr/lib64/ruby/gems/1.8/gems/rack-1.0.1/lib/rack/handler/webrick.rb:14:in`run'
/usr/lib64/ruby/gems/1.8/gems/rails-2.3.2/lib/commands/server.rb:111
/usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
/usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in`require'
script/server:3

/home/deven/rweb/project/spot-us/vendor/plugins/right_aws/lib/awsbase/right_awsbase.rb:217:in `init'
/home/deven/rweb/project/spot-us/vendor/plugins/right_aws/lib/s3/right_s3_interface.rb:81:in`initialize'
/home/deven/rweb/project/spot-us/vendor/plugins/right_aws/lib/s3/right_s3.rb:65:in `new'
/home/deven/rweb/project/spot-us/vendor/plugins/right_aws/lib/s3/right_s3.rb:65:in`initialize'
/home/deven/rweb/project/spot-us/vendor/plugins/paperclip/lib/paperclip/storage.rb:128:in `new'
/home/deven/rweb/project/spot-us/vendor/plugins/paperclip/lib/paperclip/storage.rb:128:in`s3'
/home/deven/rweb/project/spot-us/vendor/plugins/paperclip/lib/paperclip/storage.rb:134:in `s3_bucket'
/home/deven/rweb/project/spot-us/vendor/plugins/paperclip/lib/paperclip/storage.rb:166:in`flush_writes'
/home/deven/rweb/project/spot-us/vendor/plugins/paperclip/lib/paperclip/storage.rb:163:in `each'
/home/deven/rweb/project/spot-us/vendor/plugins/paperclip/lib/paperclip/storage.rb:163:in`flush_writes'
/home/deven/rweb/project/spot-us/vendor/plugins/paperclip/lib/paperclip/attachment.rb:138:in `save'
/home/deven/rweb/project/spot-us/vendor/plugins/paperclip/lib/paperclip.rb:242:in`send'
/home/deven/rweb/project/spot-us/vendor/plugins/paperclip/lib/paperclip.rb:242:in `save_attached_files'
/home/deven/rweb/project/spot-us/vendor/plugins/paperclip/lib/paperclip.rb:235:in`each_attachment'
/home/deven/rweb/project/spot-us/vendor/plugins/paperclip/lib/paperclip.rb:234:in `each'
/home/deven/rweb/project/spot-us/vendor/plugins/paperclip/lib/paperclip.rb:234:in`each_attachment'
/home/deven/rweb/project/spot-us/vendor/plugins/paperclip/lib/paperclip.rb:241:in `save_attached_files'
/usr/lib64/ruby/gems/1.8/gems/activesupport-2.3.2/lib/active_support/callbacks.rb:178:in`send'
/usr/lib64/ruby/gems/1.8/gems/activesupport-2.3.2/lib/active_support/callbacks.rb:178:in `evaluate_method'
/usr/lib64/ruby/gems/1.8/gems/activesupport-2.3.2/lib/active_support/callbacks.rb:166:in`call'
/usr/lib64/ruby/gems/1.8/gems/activesupport-2.3.2/lib/active_support/callbacks.rb:93:in `run'
/usr/lib64/ruby/gems/1.8/gems/activesupport-2.3.2/lib/active_support/callbacks.rb:92:in`each'
/usr/lib64/ruby/gems/1.8/gems/activesupport-2.3.2/lib/active_support/callbacks.rb:92:in `send'
/usr/lib64/ruby/gems/1.8/gems/activesupport-2.3.2/lib/active_support/callbacks.rb:92:in`run'
/usr/lib64/ruby/gems/1.8/gems/activesupport-2.3.2/lib/active_support/callbacks.rb:276:in `run_callbacks'
/usr/lib64/ruby/gems/1.8/gems/activerecord-2.3.2/lib/active_record/callbacks.rb:344:in`callback'
/usr/lib64/ruby/gems/1.8/gems/activerecord-2.3.2/lib/active_record/callbacks.rb:251:in `create_or_update'
/usr/lib64/ruby/gems/1.8/gems/activerecord-2.3.2/lib/active_record/base.rb:2539:in`save_without_validation'
/usr/lib64/ruby/gems/1.8/gems/activerecord-2.3.2/lib/active_record/validations.rb:1009:in `save_without_dirty'
/usr/lib64/ruby/gems/1.8/gems/activerecord-2.3.2/lib/active_record/dirty.rb:79:in`save_without_transactions'
/usr/lib64/ruby/gems/1.8/gems/activerecord-2.3.2/lib/active_record/transactions.rb:229:in `send'
/usr/lib64/ruby/gems/1.8/gems/activerecord-2.3.2/lib/active_record/transactions.rb:229:in`with_transaction_returning_status'
/usr/lib64/ruby/gems/1.8/gems/activerecord-2.3.2/lib/active_record/connection_adapters/abstract/database_statements.rb:136:in `transaction'
/usr/lib64/ruby/gems/1.8/gems/activerecord-2.3.2/lib/active_record/transactions.rb:182:in`transaction'
/usr/lib64/ruby/gems/1.8/gems/activerecord-2.3.2/lib/active_record/transactions.rb:228:in `with_transaction_returning_status'
/usr/lib64/ruby/gems/1.8/gems/activerecord-2.3.2/lib/active_record/transactions.rb:196:in`save'
/usr/lib64/ruby/gems/1.8/gems/activerecord-2.3.2/lib/active_record/transactions.rb:208:in `rollback_active_record_state!'
/usr/lib64/ruby/gems/1.8/gems/activerecord-2.3.2/lib/active_record/transactions.rb:196:in`save'
/home/deven/rweb/project/spot-us/vendor/plugins/response_for_rc/lib/ardes/response_for_rc/actions.rb:39:in `create'
/usr/lib64/ruby/gems/1.8/gems/actionpack-2.3.2/lib/action_controller/base.rb:1322:in`send'
/usr/lib64/ruby/gems/1.8/gems/actionpack-2.3.2/lib/action_controller/base.rb:1322:in `perform_action_without_filters'
/usr/lib64/ruby/gems/1.8/gems/actionpack-2.3.2/lib/action_controller/filters.rb:617:in`call_filters'
/usr/lib64/ruby/gems/1.8/gems/actionpack-2.3.2/lib/action_controller/filters.rb:610:in `perform_action_without_benchmark'
/usr/lib64/ruby/gems/1.8/gems/actionpack-2.3.2/lib/action_controller/benchmarking.rb:68:in`perform_action_without_rescue'
/usr/lib64/ruby/gems/1.8/gems/activesupport-2.3.2/lib/active_support/core_ext/benchmark.rb:17:in `ms'
/usr/lib64/ruby/gems/1.8/gems/activesupport-2.3.2/lib/active_support/core_ext/benchmark.rb:10:in`realtime'
/usr/lib64/ruby/gems/1.8/gems/activesupport-2.3.2/lib/active_support/core_ext/benchmark.rb:17:in `ms'
/usr/lib64/ruby/gems/1.8/gems/actionpack-2.3.2/lib/action_controller/benchmarking.rb:68:in`perform_action_without_rescue'
/usr/lib64/ruby/gems/1.8/gems/actionpack-2.3.2/lib/action_controller/rescue.rb:160:in `perform_action_without_flash'
/usr/lib64/ruby/gems/1.8/gems/actionpack-2.3.2/lib/action_controller/flash.rb:141:in`perform_action'
/usr/lib64/ruby/gems/1.8/gems/actionpack-2.3.2/lib/action_controller/base.rb:523:in `send'
/usr/lib64/ruby/gems/1.8/gems/actionpack-2.3.2/lib/action_controller/base.rb:523:in`process_without_filters'
/usr/lib64/ruby/gems/1.8/gems/actionpack-2.3.2/lib/action_controller/filters.rb:606:in `sass_old_process'
/usr/lib64/ruby/gems/1.8/gems/haml-2.2.16/lib/sass/plugin/rails.rb:19:in`process'
/usr/lib64/ruby/gems/1.8/gems/actionpack-2.3.2/lib/action_controller/base.rb:391:in `process'
/usr/lib64/ruby/gems/1.8/gems/actionpack-2.3.2/lib/action_controller/base.rb:386:in`call'
/usr/lib64/ruby/gems/1.8/gems/actionpack-2.3.2/lib/action_controller/routing/route_set.rb:433:in `call'
/usr/lib64/ruby/gems/1.8/gems/actionpack-2.3.2/lib/action_controller/dispatcher.rb:88:in`dispatch'
/usr/lib64/ruby/gems/1.8/gems/actionpack-2.3.2/lib/action_controller/dispatcher.rb:111:in `_call'
/usr/lib64/ruby/gems/1.8/gems/actionpack-2.3.2/lib/action_controller/dispatcher.rb:82:in`initialize'
/usr/lib64/ruby/gems/1.8/gems/activerecord-2.3.2/lib/active_record/query_cache.rb:29:in `call'
/usr/lib64/ruby/gems/1.8/gems/activerecord-2.3.2/lib/active_record/query_cache.rb:29:in`call'
/usr/lib64/ruby/gems/1.8/gems/activerecord-2.3.2/lib/active_record/connection_adapters/abstract/query_cache.rb:34:in `cache'
/usr/lib64/ruby/gems/1.8/gems/activerecord-2.3.2/lib/active_record/query_cache.rb:9:in`cache'
/usr/lib64/ruby/gems/1.8/gems/activerecord-2.3.2/lib/active_record/query_cache.rb:28:in `call'
/usr/lib64/ruby/gems/1.8/gems/activerecord-2.3.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:361:in`call'
/usr/lib64/ruby/gems/1.8/gems/rack-1.0.1/lib/rack/head.rb:9:in `call'
/usr/lib64/ruby/gems/1.8/gems/rack-1.0.1/lib/rack/methodoverride.rb:24:in`call'
/usr/lib64/ruby/gems/1.8/gems/actionpack-2.3.2/lib/action_controller/params_parser.rb:15:in `call'
/home/deven/rweb/project/spot-us/vendor/plugins/facebooker/lib/rack/facebook.rb:43:in`call'
/usr/lib64/ruby/gems/1.8/gems/actionpack-2.3.2/lib/action_controller/rewindable_input.rb:25:in `call'
/usr/lib64/ruby/gems/1.8/gems/actionpack-2.3.2/lib/action_controller/session/cookie_store.rb:93:in`call'
/usr/lib64/ruby/gems/1.8/gems/actionpack-2.3.2/lib/action_controller/reloader.rb:9:in `call'
/usr/lib64/ruby/gems/1.8/gems/actionpack-2.3.2/lib/action_controller/failsafe.rb:11:in`call'
/usr/lib64/ruby/gems/1.8/gems/rack-1.0.1/lib/rack/lock.rb:11:in `call'
/usr/lib64/ruby/gems/1.8/gems/rack-1.0.1/lib/rack/lock.rb:11:in`synchronize'
/usr/lib64/ruby/gems/1.8/gems/rack-1.0.1/lib/rack/lock.rb:11:in `call'
/usr/lib64/ruby/gems/1.8/gems/actionpack-2.3.2/lib/action_controller/dispatcher.rb:106:in`call'
/usr/lib64/ruby/gems/1.8/gems/rails-2.3.2/lib/rails/rack/static.rb:31:in `call'
/usr/lib64/ruby/gems/1.8/gems/rack-1.0.1/lib/rack/urlmap.rb:46:in`call'
/usr/lib64/ruby/gems/1.8/gems/rack-1.0.1/lib/rack/urlmap.rb:40:in `each'
/usr/lib64/ruby/gems/1.8/gems/rack-1.0.1/lib/rack/urlmap.rb:40:in`call'
/usr/lib64/ruby/gems/1.8/gems/rails-2.3.2/lib/rails/rack/log_tailer.rb:17:in `call'
/usr/lib64/ruby/gems/1.8/gems/rack-1.0.1/lib/rack/content_length.rb:13:in`call'
/usr/lib64/ruby/gems/1.8/gems/rack-1.0.1/lib/rack/handler/webrick.rb:50:in `service'
/usr/lib/ruby/1.8/webrick/httpserver.rb:104:in`service'
/usr/lib/ruby/1.8/webrick/httpserver.rb:65:in `run'
/usr/lib/ruby/1.8/webrick/server.rb:173:in`start_thread'
/usr/lib/ruby/1.8/webrick/server.rb:162:in `start'
/usr/lib/ruby/1.8/webrick/server.rb:162:in`start_thread'
/usr/lib/ruby/1.8/webrick/server.rb:95:in `start'
/usr/lib/ruby/1.8/webrick/server.rb:92:in`each'
/usr/lib/ruby/1.8/webrick/server.rb:92:in `start'
/usr/lib/ruby/1.8/webrick/server.rb:23:in`start'
/usr/lib/ruby/1.8/webrick/server.rb:82:in `start'
/usr/lib64/ruby/gems/1.8/gems/rack-1.0.1/lib/rack/handler/webrick.rb:14:in`run'
/usr/lib64/ruby/gems/1.8/gems/rails-2.3.2/lib/commands/server.rb:111
/usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
/usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in`require'
script/server:3

Request

Parameters:

{"commit"=>"Save changes",
 "channel"=>{"status"=>"hilited",
 "title"=>"TotalITSolutions",
 "channel_image"=>#File:/tmp/RackMultipart.2374.2,
 "description"=>"TotalITSolutions"}}

Show session dump

---

Response

Headers:

{"Content-Type"=>"",
 "Cache-Control"=>"no-cache"}

**Comment by Sophrinix** [comment]
you need AWS access keys are required to operate on S3 as it says.

this should be closed.
