### ISSUE TITLE
Login system on test server does not seem to work

### ISSUE THREAD

**Issue by nkokkos** [spot-us/spot-us#7]
Hi,
I created a fork of spot-us at https://github.com/nkokkos/spot-us in order to install a working test system on my pc. Therefore, I had to deactivated a number of libs (in the folder lib) and also comment out some lines in models where the S3 library is used. 
My intention was to create a working system so that I could log in as administrator and check out the admin profile and its abilites.
I froze all the gems to the version of 2.3.2 rails and made the required changed to some files (database.yml, settings.yml etc). 
After that, I prepared the system by issuing the following commands:
rake db:create
rake db:migrate
rake db:populate
and finally, 
ruby script/server to launch the the server.

The app fires up but when I try to login using any of the credentials inserted by the 
rake db:populate command (https://github.com/spot-us/spot-us/blob/master/db/fixtures/shared/users.rb) , I can't login. 

Could you please tell me if you have experienced a similar problem or is there a problem with the sessions_controller.rb?  

Thank you in advance

**Comment by eriksundelof** [comment]
The db population script doesn't work currently as we are reshaping the code a lot. The easiest way to get it working now is to register as usual and change the type of that user to Admin via the console.
