### ISSUE TITLE
error while executing server script

### ISSUE THREAD

**Issue by asim-masood** [spot-us/spot-us#8]
Following are versions I used to run Spotus App
ruby 1.8.7 (2009-06-12 patchlevel 174) [i686-linux]
gem: 1.3.3
rails: 2.3.2
rake: 0.8.4

Following is the error while executing the ./script/server
config/environments/development.rb:43:in `load_environment': undefined method`[]' for nil:NilClass (NoMethodError)

**Comment by eriksundelof** [comment]
Asim,

It has nothing to do with the codebase but you need to set the RAILS_ENV variable when you run it. 

export RAILS_ENV=development 

is what you should run in a Terminal if you are running it locally.

Best,

Erik

**Comment by madrugapt** [comment]
I'm having the same problem. I did the export but the problem still there :( any help?
